name: Deploy to Neocities
  uses: becomes/deploy-to-neocities@v1.1.13
  with:
    # Neocities API token for site to deploy to
    api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
    # Local folder to deploy to neocities
    dist_dir: # default is public
    # Delete orphaned files on neocities that don't exist in distDir
    cleanup: 
    # A glob string that prevents matched files from ever being deleted.
    protected_files: # optional
